name: CI 🚦

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
      - name: Setup Go 📦
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.2
      - name: Install dependencies 📦
        run: go get .
      - name: Test 🧪
        run: go test -json > results.json
      - name: Upload results 📤
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: results.json
