name: CI 🚦

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GO_VERSION: "1.23"

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
      - name: Setup Go 📦
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
      - name: Install dependencies 📦
        run: go mod download && go mod verify
      - name: Install Playwright 📦
        run: |
          go install github.com/playwright-community/playwright-go/cmd/playwright@latest
          playwright install --with-deps
      - name: Test 🧪
        run: go test ./... -json > results.json
        env:
          EDUBASE_EMAIL: ${{ secrets.EDUBASE_EMAIL }}
          EDUBASE_PASSWORD: ${{ secrets.EDUBASE_PASSWORD }}
          EDUBASE_BOOK_ID: ${{ secrets.EDUBASE_BOOK_ID }}
          CI: "true"
      - name: Upload results 📤
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: results.json
